/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package paperrockscissors;

import paperrockscissors.io.CLI;
import paperrockscissors.io.IOInterface;
import paperrockscissors.players.*;
import paperrockscissors.players.factories.ComputerPlayerBlueprint;
import paperrockscissors.players.factories.ComputerPlayerFactory;
import paperrockscissors.players.factories.HumanPlayerFactory;
import paperrockscissors.rules.DefaultRules;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        IOInterface cli = new CLI(new Scanner(System.in));
        HumanPlayerFactory humanPlayerFactory = new HumanPlayerFactory(cli);
        ComputerPlayerFactory computerPlayerFactory = new ComputerPlayerFactory();

        Player humanPlayer = humanPlayerFactory.create();
        Player computerPlayer = computerPlayerFactory.create(ComputerPlayerBlueprint.RANDOM_COMPUTER_PLAYER, "computron");

        Game defaultGame = new Game(cli, new DefaultRules(), humanPlayer, computerPlayer);
        defaultGame.nextRound();
    }
}
